### ISSUE TITLE
TypeError: Cannot read property 'statusCode' of undefined

### ISSUE THREAD

**Issue by yinguangyao** [fastify/fastify-static#154]
## 🐛 Bug Report

When I open the `localhost:3000`, static resources failed to load, and throw this error.

```js
/Users/xxxx/Desktop/project/is-admin/node_modules/fastify-static/index.js:75
        return reply.raw.statusCode
                         ^
TypeError: Cannot read property 'statusCode' of undefined
    at PassThrough.get (/Users/guangyaoyin/Desktop/project/is-admin/node_modules/fastify-static/index.js:75:26)
    at SendStream.isCachable (/Users/guangyaoyin/Desktop/project/is-admin/node_modules/send/index.js:404:29)
    at SendStream.send (/Users/guangyaoyin/Desktop/project/is-admin/node_modules/send/index.js:636:14)
    at onstat (/Users/guangyaoyin/Desktop/project/is-admin/node_modules/send/index.js:729:10)
    at FSReqCallback.oncomplete (fs.js:159:5)
[nodemon] app crashed - waiting for file changes before starting...
```

![image](https://user-images.githubusercontent.com/16210045/97111987-c82f5380-171c-11eb-9c6c-cb927697e8d8.png)

But I can access static resources directly：

![image](https://user-images.githubusercontent.com/16210045/97112011-f44ad480-171c-11eb-9130-7d443c61b120.png)

## To Reproduce
My code is as follows:

![image](https://user-images.githubusercontent.com/16210045/97111889-43dcd080-171c-11eb-9a16-82a1806ce635.png)

![image](https://user-images.githubusercontent.com/16210045/97112065-3d9b2400-171d-11eb-96d6-310bcedaddb7.png)

## Your Environment

- *node version*: 12.14.0
- *fastify version*: ^2.3.0
- *os*: Mac
- *fastify-static*: ^3.0.2

**Comment by mcollina** [comment]
Please fastify-static v2.x with fastify v2.

**Comment by climba03003** [comment]
Resolved as it is mismatch of package version usage.
