### ISSUE TITLE
reply.notFound is not a function

### ISSUE THREAD

**Issue by medez** [fastify/fastify-static#49]
Hello, 

I use fastify-static 0.6.0 with fastify 1.2.1. When I try to call an unknown static file, I don't receive any 404 error, and my application crashed after this error : 

TypeError: reply.notFound is not a function
  at SendStream.<anonymous> (/var/www/node_modules/fastify-static/index.js:42:15)
  at emitOne (events.js:116:13)
  at SendStream.emit (events.js:211:7)
  at SendStream.error (/var/www/node_modules/send/index.js:270:17)
  at SendStream.onStatError (/var/www/node_modules/send/index.js:421:12)
  at onstat (/var/www/node_modules/send/index.js:727:26)
  at FSReqWrap.oncomplete (fs.js:152:21)

**Comment by delvedor** [comment]
Hi! If you update to the latest version the problem should be fixed.
If you can't, try install [`fastify-sensible`](https://github.com/fastify/fastify-sensible).

**Comment by mcollina** [comment]
you should update fastify-static. It's at version 0.10.0, and it's not compatible with 1.0.0 :/.

**Comment by medez** [comment]
OK Thanks. I had just installed fastify-static, it's strange the installed version not to be the last one...
